
# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#  name = "github.com/x/y"
#  version = "2.4.0"


[[constraint]]
  name = "cirello.io/supervisor"
  version = "0.5.3"

[[constraint]]
  name = "github.com/aws/aws-sdk-go"
  version = "1.12.34"

[[constraint]]
  name = "github.com/boltdb/bolt"
  version = "1.3.1"

[[constraint]]
  branch = "master"
  name = "github.com/c0ze/runner"

[[constraint]]
  branch = "master"
  name = "github.com/dghubble/go-twitter"

[[constraint]]
  name = "github.com/dghubble/oauth1"
  version = "0.4.0"

[[constraint]]
  name = "github.com/dgrijalva/jwt-go"
  version = "3.1.0"

[[constraint]]
  name = "github.com/fsouza/go-dockerclient"
  version = "1.1.0"

[[constraint]]
  name = "github.com/garyburd/redigo"
  version = "1.3.0"

[[constraint]]
  name = "github.com/giantswarm/semver-bump"
  version = "1.1.1"

[[constraint]]
  name = "github.com/gin-gonic/gin"
  version = "1.2.0"

[[constraint]]
  branch = "master"
  name = "github.com/go-openapi/errors"

[[constraint]]
  branch = "master"
  name = "github.com/go-openapi/loads"

[[constraint]]
  branch = "master"
  name = "github.com/go-openapi/runtime"

[[constraint]]
  branch = "master"
  name = "github.com/go-openapi/spec"

[[constraint]]
  branch = "master"
  name = "github.com/go-openapi/strfmt"

[[constraint]]
  branch = "master"
  name = "github.com/go-openapi/swag"

[[constraint]]
  branch = "master"
  name = "github.com/go-openapi/validate"

[[constraint]]
  name = "github.com/go-resty/resty"
  version = "1.0.0"

[[constraint]]
  name = "github.com/go-sql-driver/mysql"
  version = "1.3.0"

[[constraint]]
  branch = "master"
  name = "github.com/golang/groupcache"

[[constraint]]
  branch = "master"
  name = "github.com/google/btree"

[[constraint]]
  branch = "master"
  name = "github.com/iron-io/functions_go"

[[constraint]]
  branch = "master"
  name = "github.com/iron-io/iron_go3"

[[constraint]]
  branch = "master"
  name = "github.com/jmoiron/jsonq"

[[constraint]]
  branch = "master"
  name = "github.com/lib/pq"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.0"

[[constraint]]
  name = "github.com/satori/go.uuid"
  version = "1.1.0"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.0.3"

[[constraint]]
  name = "github.com/spf13/viper"
  version = "1.0.0"

[[constraint]]
  name = "github.com/urfave/cli"
  version = "1.20.0"

[[constraint]]
  branch = "master"
  name = "golang.org/x/crypto"

[[constraint]]
  branch = "master"
  name = "golang.org/x/net"

[[constraint]]
  branch = "v2"
  name = "gopkg.in/mgo.v2"

[[constraint]]
  branch = "v2"
  name = "gopkg.in/yaml.v2"
